name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Run tests without proposals
      run: cargo test -- -q
    - name: Run tests with proposals enabled
      run: cargo test --features=proposals -- -q
    - name: Run `clippy check`
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features --all-targets
